GAWB-937 Validates wdls against the appropriate version of wdl4s on import
broadinstitute/agora pull request #183
Opened 2017-04-13 18:49 UTC by helgridly

- [ ] **Submitter**: Include the JIRA issue number in the PR description
- [ ] **Submitter**: Make sure Swagger is updated if API changes
- [ ] **Submitter**: If updating admin endpoints, also update [firecloud-admin-cli](https://github.com/broadinstitute/firecloud-admin-cli)
- [ ] **Submitter**: Check documentation and code comments. Add explanatory PR comments if helpful.
- [ ] **Submitter**: JIRA ticket checks:
  * Acceptance criteria exists and is met
  * Note any changes to implementation from the description
  * Add notes on what you've tested
- [ ] **Submitter**: Update RC_XXX release ticket with any config or environment changes necessary
- [ ] **Submitter**: Update FISMA documentation if changes to:
  * Authentication
  * Authorization
  * Encryption
  * Audit trails
- [ ] **Submitter**: If you're adding new libraries, sign us up to security updates for them
- [ ] Tell the tech lead (TL) that the PR exists if they wants to look at it
- [ ] Anoint a lead reviewer (LR). **Assign PR to LR**
* Review cycle:
  * LR reviews
  * Rest of team may comment on PR at will
  * **LR assigns to submitter** for feedback fixes
  * Submitter rebases to develop again if necessary
  * Submitter makes further commits. DO NOT SQUASH
  * Submitter updates documentation as needed
  * Submitter **reassigns to LR** for further feedback
- [ ] **TL** sign off
- [ ] **LR** sign off
- [ ] **Product Owner** sign off
- [ ] **Assign to submitter** to finalize
- [ ] **Submitter**: Verify all tests go green, including CI tests
- [ ] **Submitter**: Squash commits and merge to develop
- [ ] **Submitter**: Delete branch after merge
- [ ] **Submitter**: **Test this change works on dev environment after deployment**. YOU own getting it fixed if dev isn't working for ANY reason!
- [ ] **Submitter**: Verify swagger UI on dev environment still works after deployment
- [ ] **Submitter**: Inform other teams of any API changes via hipchat and/or email
- [ ] **Submitter**: Mark JIRA issue as resolved once this checklist is completed

2017-04-14 14:26 UTC, ansingh7115 commented on src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraImportSpec.scala
>      }
Is there a reason we are leaving some of the code commented out rather than just deleting it?

2017-04-14 17:23 UTC, helgridly commented on src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraImportSpec.scala
>      }
it was commented out before, but no, not really!

2017-04-14 19:41 UTC, ansingh7115 commented on src/test/scala/org/broadinstitute/dsde/agora/server/webservice/AgoraImportSpec.scala
>      }
you commented out line 22

2017-04-18 17:23 UTC, dvoet requested changes

2017-04-18 17:23 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala
> +      case Success(false) => Failure(ValidationException("Agora doesn't support imports in WDLs"))
I would say "WDL imports not yet supported." No need to mention Agora.

2017-04-18 17:23 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala
> +    val wdlImportCheck = checkWdlHasNoImports(wdl)
why not inline wdlImportCheck? As it stands now, it also runs, although ignored, for a configuration.

2017-04-18 17:23 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala
> +    val wdl = agoraEntity.payload.get
this will not be wdl in the case of configs

2017-04-18 17:23 UTC, dvoet commented on src/main/scala/org/broadinstitute/dsde/agora/server/business/AgoraBusiness.scala
> +    val wdlLoads = agoraEntity.entityType.get match {
I know the .get was there, but seems like a bad practice... why not build Some(...) into the case statements? Or at least getOrElse.

2017-04-18 17:50 UTC, helgridly commented
@dvoet @ansingh7115 ready for re-review thx

2017-04-18 19:37 UTC, ansingh7115 approved these changes

2017-04-19 17:35 UTC, helgridly commented
doge gave me a physical 👍

2017-04-24 14:55 UTC, merged